### ISSUE TITLE
Compare pre-release and release

### ISSUE THREAD

**Issue by QuentinRoy** [leohihimax/node-version-compare#3]
Thank you for this very useful utility.

I run into the following bug: `compareVersions("1.0.0", "1.0.0-beta.2")` returns `-1`, indicating that beta.2 comes after 1.0.0. Obviously this is incorrect, the beta comes before.

**Comment by leohihimax** [comment]
@QuentinRoy Thank you for your feedback, I just fixed this bug in the latest version(1.0.2). You can use it right now.
